version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - java -version
      - echo "setting up global environment variables"
      - export BUILDDIR="./build"
      - export APPDIR="./eac-core/eac"
      - echo "updating container packages"
      - apt-get update -y
      - echo "installing container dependencies"
      - apt-get install maven ant rsync unzip foodcritic -y
  build:
    commands:
      - export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:bin/javac::")
      - echo "setting java home to ${JAVA_HOME}"
      - test -d /root/.m2 && echo "/root/.m2 exist" || mkdir /root/.m2
      - cp -Rp ./configs/settings.xml /root/.m2/settings.xml
      - sed -i "s/|NEXUS_USERNAME|/admin/g" /root/.m2/settings.xml
      - sed -i "s/|NEXUS_PASSWORD|/admin123/g" /root/.m2/settings.xml
      - sed -i "s/|NEXUS_URL|/http:\/\/nexus.eps-management.the-infra.com:8081\/nexus\/content\/groups\/public\//g" /root/.m2/settings.xml
      - echo "setting nexus username to admin on repository nexus.eps-management.the-infra.com:8081"
      - mkdir $BUILDDIR
      - mkdir $BUILDDIR/target
      - rsync -avz "${APPDIR}/" $BUILDDIR/target/
      - cd $BUILDDIR/target/eacBuild
#      - mvn --batch-mode clean install -U
#      - ls -lh
      #- mvn clean -X release:prepare release:perform

artifacts:
  files:
    - './**/*'
    - './configs/**/*'
    - './eac-core/**/*'
    - './pipeline-template/**/*'
    - './build/target/**/*'