version: 0.2

phases:
  pre_build:
    commands:
       - echo "setting up global environment variables"
       - export BUILDDIR="./build"
       - export APPDIR="./eac-core/eac/eacBuild"
       - echo "updating container packages"
       - apt-get update -y
       - echo "installing container dependencies"
       - apt-get install maven ant rsync unzip foodcritic -y
  build:
    commands:
      - export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:bin/javac::")
      - echo "setting java home to ${JAVA_HOME}"
      - mkdir $BUILDDIR
      - mkdir $BUILDDIR/target
      - cp -Rp $BUILDDIR/eacBuild $BUILDDIR/target/eacBuild
      - rsync -avz "${APPDIR}/eacBuild/" $BUILDDIR/target/eacBuild
      - cd $BUILDDIR/target/eacBuild
      - mvn --batch-mode clean install
      - ls -lh
      #- mvn clean -X release:prepare release:perform

artifacts:
  files:
     - './configs/**/*'
     - './eac-core/**/*'
     - './pipeline-template/**/*'
     - './build/target/**/*'