//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.29 at 05:07:04 PM BST 
//


package com.oup.eac.domain.migrationtool.beans;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for adminPromotion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adminPromotion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="applicableProducts" type="{}adminOrderProduct" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="categoryRule" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="coupons" type="{}adminCoupon" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cumulative" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="custom1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom9" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerGroupRule" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="customerRule" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dateAdded" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="manufacturerRule" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxUse" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numCategories" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numCoupons" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numCustomerGroups" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numCustomers" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numExpressions" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numManufacturers" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numProducts" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="orderTotalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="productRule" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="requiresCoupon" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adminPromotion", propOrder = {
    "active",
    "applicableProducts",
    "categoryRule",
    "coupons",
    "cumulative",
    "custom1",
    "custom10",
    "custom2",
    "custom3",
    "custom4",
    "custom5",
    "custom6",
    "custom7",
    "custom8",
    "custom9",
    "customerGroupRule",
    "customerRule",
    "dateAdded",
    "description",
    "endDate",
    "id",
    "lastModified",
    "manufacturerRule",
    "maxUse",
    "name",
    "numCategories",
    "numCoupons",
    "numCustomerGroups",
    "numCustomers",
    "numExpressions",
    "numManufacturers",
    "numProducts",
    "orderTotalCode",
    "productRule",
    "requiresCoupon",
    "startDate"
})
public class AdminPromotion {

    protected boolean active;
    @XmlElement(nillable = true)
    protected List<AdminOrderProduct> applicableProducts;
    protected int categoryRule;
    @XmlElement(nillable = true)
    protected List<AdminCoupon> coupons;
    protected boolean cumulative;
    protected String custom1;
    protected String custom10;
    protected String custom2;
    protected String custom3;
    protected String custom4;
    protected String custom5;
    protected String custom6;
    protected String custom7;
    protected String custom8;
    protected String custom9;
    protected int customerGroupRule;
    protected int customerRule;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateAdded;
    protected String description;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    protected int id;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModified;
    protected int manufacturerRule;
    protected int maxUse;
    protected String name;
    protected int numCategories;
    protected int numCoupons;
    protected int numCustomerGroups;
    protected int numCustomers;
    protected int numExpressions;
    protected int numManufacturers;
    protected int numProducts;
    protected String orderTotalCode;
    protected int productRule;
    protected boolean requiresCoupon;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;

    /**
     * Gets the value of the active property.
     * 
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the applicableProducts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicableProducts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicableProducts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminOrderProduct }
     * 
     * 
     */
    public List<AdminOrderProduct> getApplicableProducts() {
        if (applicableProducts == null) {
            applicableProducts = new ArrayList<AdminOrderProduct>();
        }
        return this.applicableProducts;
    }

    /**
     * Gets the value of the categoryRule property.
     * 
     */
    public int getCategoryRule() {
        return categoryRule;
    }

    /**
     * Sets the value of the categoryRule property.
     * 
     */
    public void setCategoryRule(int value) {
        this.categoryRule = value;
    }

    /**
     * Gets the value of the coupons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coupons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoupons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminCoupon }
     * 
     * 
     */
    public List<AdminCoupon> getCoupons() {
        if (coupons == null) {
            coupons = new ArrayList<AdminCoupon>();
        }
        return this.coupons;
    }

    /**
     * Gets the value of the cumulative property.
     * 
     */
    public boolean isCumulative() {
        return cumulative;
    }

    /**
     * Sets the value of the cumulative property.
     * 
     */
    public void setCumulative(boolean value) {
        this.cumulative = value;
    }

    /**
     * Gets the value of the custom1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * Sets the value of the custom1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom1(String value) {
        this.custom1 = value;
    }

    /**
     * Gets the value of the custom10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom10() {
        return custom10;
    }

    /**
     * Sets the value of the custom10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom10(String value) {
        this.custom10 = value;
    }

    /**
     * Gets the value of the custom2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * Sets the value of the custom2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom2(String value) {
        this.custom2 = value;
    }

    /**
     * Gets the value of the custom3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * Sets the value of the custom3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom3(String value) {
        this.custom3 = value;
    }

    /**
     * Gets the value of the custom4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * Sets the value of the custom4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom4(String value) {
        this.custom4 = value;
    }

    /**
     * Gets the value of the custom5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * Sets the value of the custom5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom5(String value) {
        this.custom5 = value;
    }

    /**
     * Gets the value of the custom6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom6() {
        return custom6;
    }

    /**
     * Sets the value of the custom6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom6(String value) {
        this.custom6 = value;
    }

    /**
     * Gets the value of the custom7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom7() {
        return custom7;
    }

    /**
     * Sets the value of the custom7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom7(String value) {
        this.custom7 = value;
    }

    /**
     * Gets the value of the custom8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom8() {
        return custom8;
    }

    /**
     * Sets the value of the custom8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom8(String value) {
        this.custom8 = value;
    }

    /**
     * Gets the value of the custom9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom9() {
        return custom9;
    }

    /**
     * Sets the value of the custom9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom9(String value) {
        this.custom9 = value;
    }

    /**
     * Gets the value of the customerGroupRule property.
     * 
     */
    public int getCustomerGroupRule() {
        return customerGroupRule;
    }

    /**
     * Sets the value of the customerGroupRule property.
     * 
     */
    public void setCustomerGroupRule(int value) {
        this.customerGroupRule = value;
    }

    /**
     * Gets the value of the customerRule property.
     * 
     */
    public int getCustomerRule() {
        return customerRule;
    }

    /**
     * Sets the value of the customerRule property.
     * 
     */
    public void setCustomerRule(int value) {
        this.customerRule = value;
    }

    /**
     * Gets the value of the dateAdded property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAdded() {
        return dateAdded;
    }

    /**
     * Sets the value of the dateAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAdded(XMLGregorianCalendar value) {
        this.dateAdded = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModified(XMLGregorianCalendar value) {
        this.lastModified = value;
    }

    /**
     * Gets the value of the manufacturerRule property.
     * 
     */
    public int getManufacturerRule() {
        return manufacturerRule;
    }

    /**
     * Sets the value of the manufacturerRule property.
     * 
     */
    public void setManufacturerRule(int value) {
        this.manufacturerRule = value;
    }

    /**
     * Gets the value of the maxUse property.
     * 
     */
    public int getMaxUse() {
        return maxUse;
    }

    /**
     * Sets the value of the maxUse property.
     * 
     */
    public void setMaxUse(int value) {
        this.maxUse = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the numCategories property.
     * 
     */
    public int getNumCategories() {
        return numCategories;
    }

    /**
     * Sets the value of the numCategories property.
     * 
     */
    public void setNumCategories(int value) {
        this.numCategories = value;
    }

    /**
     * Gets the value of the numCoupons property.
     * 
     */
    public int getNumCoupons() {
        return numCoupons;
    }

    /**
     * Sets the value of the numCoupons property.
     * 
     */
    public void setNumCoupons(int value) {
        this.numCoupons = value;
    }

    /**
     * Gets the value of the numCustomerGroups property.
     * 
     */
    public int getNumCustomerGroups() {
        return numCustomerGroups;
    }

    /**
     * Sets the value of the numCustomerGroups property.
     * 
     */
    public void setNumCustomerGroups(int value) {
        this.numCustomerGroups = value;
    }

    /**
     * Gets the value of the numCustomers property.
     * 
     */
    public int getNumCustomers() {
        return numCustomers;
    }

    /**
     * Sets the value of the numCustomers property.
     * 
     */
    public void setNumCustomers(int value) {
        this.numCustomers = value;
    }

    /**
     * Gets the value of the numExpressions property.
     * 
     */
    public int getNumExpressions() {
        return numExpressions;
    }

    /**
     * Sets the value of the numExpressions property.
     * 
     */
    public void setNumExpressions(int value) {
        this.numExpressions = value;
    }

    /**
     * Gets the value of the numManufacturers property.
     * 
     */
    public int getNumManufacturers() {
        return numManufacturers;
    }

    /**
     * Sets the value of the numManufacturers property.
     * 
     */
    public void setNumManufacturers(int value) {
        this.numManufacturers = value;
    }

    /**
     * Gets the value of the numProducts property.
     * 
     */
    public int getNumProducts() {
        return numProducts;
    }

    /**
     * Sets the value of the numProducts property.
     * 
     */
    public void setNumProducts(int value) {
        this.numProducts = value;
    }

    /**
     * Gets the value of the orderTotalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTotalCode() {
        return orderTotalCode;
    }

    /**
     * Sets the value of the orderTotalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTotalCode(String value) {
        this.orderTotalCode = value;
    }

    /**
     * Gets the value of the productRule property.
     * 
     */
    public int getProductRule() {
        return productRule;
    }

    /**
     * Sets the value of the productRule property.
     * 
     */
    public void setProductRule(int value) {
        this.productRule = value;
    }

    /**
     * Gets the value of the requiresCoupon property.
     * 
     */
    public boolean isRequiresCoupon() {
        return requiresCoupon;
    }

    /**
     * Sets the value of the requiresCoupon property.
     * 
     */
    public void setRequiresCoupon(boolean value) {
        this.requiresCoupon = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

}
