//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.29 at 05:07:04 PM BST 
//


package com.oup.eac.domain.migrationtool.beans;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for adminOrder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adminOrder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="affiliateId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingAddrFormatId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="billingAddrFormatTemplate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingAddrId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="billingCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingCompany" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingFormattedAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingPostcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingStreetAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingStreetAddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingSuburb" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingTelephone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingTelephone1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ccCVV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ccExpires" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ccNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ccOwner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ccType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="couponIds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currency" type="{}adminCurrency" minOccurs="0"/>
 *         &lt;element name="currencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currencyValue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="custom1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerAddrFormatId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="customerAddrFormatTemplate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerAddrId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="customerCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerCompany" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerFormattedAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="customerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerPostcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerStreetAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerStreetAddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerSuburb" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerTelephone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerTelephone1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateFinished" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="datePurchased" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="deliveryAddrFormatId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="deliveryAddrFormatTemplate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryAddrId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="deliveryCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryCompany" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryCountryObject" type="{}adminCountry" minOccurs="0"/>
 *         &lt;element name="deliveryEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryFormattedAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryPostcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryStreetAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryStreetAddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliverySuburb" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryTelephone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryTelephone1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryZoneObject" type="{}adminZone" minOccurs="0"/>
 *         &lt;element name="encKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="formattedTotalIncTax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="invoiceFilename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="lifecycleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="locale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numProducts" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderProducts" type="{}adminOrderProduct" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="orderReturns" type="{}adminOrderReturn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="orderTotals" type="{}adminOrderTotal" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="paymentMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="paymentModuleCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pointsAwarded" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pointsRedeemed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pointsReservationId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="promotionIds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shippingMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shippingModuleCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shippingQuote" type="{}adminShippingQuote" minOccurs="0"/>
 *         &lt;element name="shippingServiceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="statusText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusTrail" type="{}adminOrderStatusHistory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="taxRateObjectArray" type="{}adminTaxRate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalExTax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totalIncTax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="trackingNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adminOrder", propOrder = {
    "affiliateId",
    "billingAddrFormatId",
    "billingAddrFormatTemplate",
    "billingAddrId",
    "billingCity",
    "billingCompany",
    "billingCountry",
    "billingEmail",
    "billingFormattedAddress",
    "billingName",
    "billingPostcode",
    "billingState",
    "billingStreetAddress",
    "billingStreetAddress1",
    "billingSuburb",
    "billingTelephone",
    "billingTelephone1",
    "ccCVV",
    "ccExpires",
    "ccNumber",
    "ccOwner",
    "ccType",
    "couponIds",
    "creator",
    "currency",
    "currencyCode",
    "currencyValue",
    "custom1",
    "custom2",
    "custom3",
    "custom4",
    "custom5",
    "customerAddrFormatId",
    "customerAddrFormatTemplate",
    "customerAddrId",
    "customerCity",
    "customerCompany",
    "customerCountry",
    "customerEmail",
    "customerFormattedAddress",
    "customerId",
    "customerName",
    "customerPostcode",
    "customerState",
    "customerStreetAddress",
    "customerStreetAddress1",
    "customerSuburb",
    "customerTelephone",
    "customerTelephone1",
    "dateFinished",
    "datePurchased",
    "deliveryAddrFormatId",
    "deliveryAddrFormatTemplate",
    "deliveryAddrId",
    "deliveryCity",
    "deliveryCompany",
    "deliveryCountry",
    "deliveryCountryObject",
    "deliveryEmail",
    "deliveryFormattedAddress",
    "deliveryName",
    "deliveryPostcode",
    "deliveryState",
    "deliveryStreetAddress",
    "deliveryStreetAddress1",
    "deliverySuburb",
    "deliveryTelephone",
    "deliveryTelephone1",
    "deliveryZoneObject",
    "encKey",
    "formattedTotalIncTax",
    "id",
    "invoiceFilename",
    "lastModified",
    "lifecycleId",
    "locale",
    "numProducts",
    "orderNumber",
    "orderProducts",
    "orderReturns",
    "orderTotals",
    "paymentMethod",
    "paymentModuleCode",
    "pointsAwarded",
    "pointsRedeemed",
    "pointsReservationId",
    "promotionIds",
    "shippingMethod",
    "shippingModuleCode",
    "shippingQuote",
    "shippingServiceCode",
    "status",
    "statusText",
    "statusTrail",
    "tax",
    "taxRateObjectArray",
    "totalExTax",
    "totalIncTax",
    "trackingNumber"
})
public class AdminOrder {

    protected String affiliateId;
    protected int billingAddrFormatId;
    protected String billingAddrFormatTemplate;
    protected int billingAddrId;
    protected String billingCity;
    protected String billingCompany;
    protected String billingCountry;
    protected String billingEmail;
    protected String billingFormattedAddress;
    protected String billingName;
    protected String billingPostcode;
    protected String billingState;
    protected String billingStreetAddress;
    protected String billingStreetAddress1;
    protected String billingSuburb;
    protected String billingTelephone;
    protected String billingTelephone1;
    protected String ccCVV;
    protected String ccExpires;
    protected String ccNumber;
    protected String ccOwner;
    protected String ccType;
    protected String couponIds;
    protected String creator;
    protected AdminCurrency currency;
    protected String currencyCode;
    protected BigDecimal currencyValue;
    protected String custom1;
    protected String custom2;
    protected String custom3;
    protected String custom4;
    protected String custom5;
    protected int customerAddrFormatId;
    protected String customerAddrFormatTemplate;
    protected int customerAddrId;
    protected String customerCity;
    protected String customerCompany;
    protected String customerCountry;
    protected String customerEmail;
    protected String customerFormattedAddress;
    protected int customerId;
    protected String customerName;
    protected String customerPostcode;
    protected String customerState;
    protected String customerStreetAddress;
    protected String customerStreetAddress1;
    protected String customerSuburb;
    protected String customerTelephone;
    protected String customerTelephone1;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateFinished;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datePurchased;
    protected int deliveryAddrFormatId;
    protected String deliveryAddrFormatTemplate;
    protected int deliveryAddrId;
    protected String deliveryCity;
    protected String deliveryCompany;
    protected String deliveryCountry;
    protected AdminCountry deliveryCountryObject;
    protected String deliveryEmail;
    protected String deliveryFormattedAddress;
    protected String deliveryName;
    protected String deliveryPostcode;
    protected String deliveryState;
    protected String deliveryStreetAddress;
    protected String deliveryStreetAddress1;
    protected String deliverySuburb;
    protected String deliveryTelephone;
    protected String deliveryTelephone1;
    protected AdminZone deliveryZoneObject;
    protected String encKey;
    protected String formattedTotalIncTax;
    protected int id;
    protected String invoiceFilename;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModified;
    protected String lifecycleId;
    protected String locale;
    protected int numProducts;
    protected String orderNumber;
    @XmlElement(nillable = true)
    protected List<AdminOrderProduct> orderProducts;
    @XmlElement(nillable = true)
    protected List<AdminOrderReturn> orderReturns;
    @XmlElement(nillable = true)
    protected List<AdminOrderTotal> orderTotals;
    protected String paymentMethod;
    protected String paymentModuleCode;
    protected int pointsAwarded;
    protected int pointsRedeemed;
    protected int pointsReservationId;
    protected String promotionIds;
    protected String shippingMethod;
    protected String shippingModuleCode;
    protected AdminShippingQuote shippingQuote;
    protected String shippingServiceCode;
    protected int status;
    protected String statusText;
    @XmlElement(nillable = true)
    protected List<AdminOrderStatusHistory> statusTrail;
    protected BigDecimal tax;
    @XmlElement(nillable = true)
    protected List<AdminTaxRate> taxRateObjectArray;
    protected BigDecimal totalExTax;
    protected BigDecimal totalIncTax;
    protected String trackingNumber;

    /**
     * Gets the value of the affiliateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliateId() {
        return affiliateId;
    }

    /**
     * Sets the value of the affiliateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliateId(String value) {
        this.affiliateId = value;
    }

    /**
     * Gets the value of the billingAddrFormatId property.
     * 
     */
    public int getBillingAddrFormatId() {
        return billingAddrFormatId;
    }

    /**
     * Sets the value of the billingAddrFormatId property.
     * 
     */
    public void setBillingAddrFormatId(int value) {
        this.billingAddrFormatId = value;
    }

    /**
     * Gets the value of the billingAddrFormatTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAddrFormatTemplate() {
        return billingAddrFormatTemplate;
    }

    /**
     * Sets the value of the billingAddrFormatTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAddrFormatTemplate(String value) {
        this.billingAddrFormatTemplate = value;
    }

    /**
     * Gets the value of the billingAddrId property.
     * 
     */
    public int getBillingAddrId() {
        return billingAddrId;
    }

    /**
     * Sets the value of the billingAddrId property.
     * 
     */
    public void setBillingAddrId(int value) {
        this.billingAddrId = value;
    }

    /**
     * Gets the value of the billingCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingCity() {
        return billingCity;
    }

    /**
     * Sets the value of the billingCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingCity(String value) {
        this.billingCity = value;
    }

    /**
     * Gets the value of the billingCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingCompany() {
        return billingCompany;
    }

    /**
     * Sets the value of the billingCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingCompany(String value) {
        this.billingCompany = value;
    }

    /**
     * Gets the value of the billingCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingCountry() {
        return billingCountry;
    }

    /**
     * Sets the value of the billingCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingCountry(String value) {
        this.billingCountry = value;
    }

    /**
     * Gets the value of the billingEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingEmail() {
        return billingEmail;
    }

    /**
     * Sets the value of the billingEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingEmail(String value) {
        this.billingEmail = value;
    }

    /**
     * Gets the value of the billingFormattedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingFormattedAddress() {
        return billingFormattedAddress;
    }

    /**
     * Sets the value of the billingFormattedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingFormattedAddress(String value) {
        this.billingFormattedAddress = value;
    }

    /**
     * Gets the value of the billingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingName() {
        return billingName;
    }

    /**
     * Sets the value of the billingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingName(String value) {
        this.billingName = value;
    }

    /**
     * Gets the value of the billingPostcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingPostcode() {
        return billingPostcode;
    }

    /**
     * Sets the value of the billingPostcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingPostcode(String value) {
        this.billingPostcode = value;
    }

    /**
     * Gets the value of the billingState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingState() {
        return billingState;
    }

    /**
     * Sets the value of the billingState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingState(String value) {
        this.billingState = value;
    }

    /**
     * Gets the value of the billingStreetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingStreetAddress() {
        return billingStreetAddress;
    }

    /**
     * Sets the value of the billingStreetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingStreetAddress(String value) {
        this.billingStreetAddress = value;
    }

    /**
     * Gets the value of the billingStreetAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingStreetAddress1() {
        return billingStreetAddress1;
    }

    /**
     * Sets the value of the billingStreetAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingStreetAddress1(String value) {
        this.billingStreetAddress1 = value;
    }

    /**
     * Gets the value of the billingSuburb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingSuburb() {
        return billingSuburb;
    }

    /**
     * Sets the value of the billingSuburb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingSuburb(String value) {
        this.billingSuburb = value;
    }

    /**
     * Gets the value of the billingTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingTelephone() {
        return billingTelephone;
    }

    /**
     * Sets the value of the billingTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingTelephone(String value) {
        this.billingTelephone = value;
    }

    /**
     * Gets the value of the billingTelephone1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingTelephone1() {
        return billingTelephone1;
    }

    /**
     * Sets the value of the billingTelephone1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingTelephone1(String value) {
        this.billingTelephone1 = value;
    }

    /**
     * Gets the value of the ccCVV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcCVV() {
        return ccCVV;
    }

    /**
     * Sets the value of the ccCVV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcCVV(String value) {
        this.ccCVV = value;
    }

    /**
     * Gets the value of the ccExpires property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcExpires() {
        return ccExpires;
    }

    /**
     * Sets the value of the ccExpires property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcExpires(String value) {
        this.ccExpires = value;
    }

    /**
     * Gets the value of the ccNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcNumber() {
        return ccNumber;
    }

    /**
     * Sets the value of the ccNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcNumber(String value) {
        this.ccNumber = value;
    }

    /**
     * Gets the value of the ccOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcOwner() {
        return ccOwner;
    }

    /**
     * Sets the value of the ccOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcOwner(String value) {
        this.ccOwner = value;
    }

    /**
     * Gets the value of the ccType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcType() {
        return ccType;
    }

    /**
     * Sets the value of the ccType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcType(String value) {
        this.ccType = value;
    }

    /**
     * Gets the value of the couponIds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponIds() {
        return couponIds;
    }

    /**
     * Sets the value of the couponIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponIds(String value) {
        this.couponIds = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreator(String value) {
        this.creator = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link AdminCurrency }
     *     
     */
    public AdminCurrency getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminCurrency }
     *     
     */
    public void setCurrency(AdminCurrency value) {
        this.currency = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the currencyValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrencyValue() {
        return currencyValue;
    }

    /**
     * Sets the value of the currencyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrencyValue(BigDecimal value) {
        this.currencyValue = value;
    }

    /**
     * Gets the value of the custom1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * Sets the value of the custom1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom1(String value) {
        this.custom1 = value;
    }

    /**
     * Gets the value of the custom2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * Sets the value of the custom2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom2(String value) {
        this.custom2 = value;
    }

    /**
     * Gets the value of the custom3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * Sets the value of the custom3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom3(String value) {
        this.custom3 = value;
    }

    /**
     * Gets the value of the custom4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * Sets the value of the custom4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom4(String value) {
        this.custom4 = value;
    }

    /**
     * Gets the value of the custom5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * Sets the value of the custom5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom5(String value) {
        this.custom5 = value;
    }

    /**
     * Gets the value of the customerAddrFormatId property.
     * 
     */
    public int getCustomerAddrFormatId() {
        return customerAddrFormatId;
    }

    /**
     * Sets the value of the customerAddrFormatId property.
     * 
     */
    public void setCustomerAddrFormatId(int value) {
        this.customerAddrFormatId = value;
    }

    /**
     * Gets the value of the customerAddrFormatTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddrFormatTemplate() {
        return customerAddrFormatTemplate;
    }

    /**
     * Sets the value of the customerAddrFormatTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddrFormatTemplate(String value) {
        this.customerAddrFormatTemplate = value;
    }

    /**
     * Gets the value of the customerAddrId property.
     * 
     */
    public int getCustomerAddrId() {
        return customerAddrId;
    }

    /**
     * Sets the value of the customerAddrId property.
     * 
     */
    public void setCustomerAddrId(int value) {
        this.customerAddrId = value;
    }

    /**
     * Gets the value of the customerCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCity() {
        return customerCity;
    }

    /**
     * Sets the value of the customerCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCity(String value) {
        this.customerCity = value;
    }

    /**
     * Gets the value of the customerCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCompany() {
        return customerCompany;
    }

    /**
     * Sets the value of the customerCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCompany(String value) {
        this.customerCompany = value;
    }

    /**
     * Gets the value of the customerCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCountry() {
        return customerCountry;
    }

    /**
     * Sets the value of the customerCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCountry(String value) {
        this.customerCountry = value;
    }

    /**
     * Gets the value of the customerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * Sets the value of the customerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEmail(String value) {
        this.customerEmail = value;
    }

    /**
     * Gets the value of the customerFormattedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerFormattedAddress() {
        return customerFormattedAddress;
    }

    /**
     * Sets the value of the customerFormattedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerFormattedAddress(String value) {
        this.customerFormattedAddress = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     */
    public int getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     */
    public void setCustomerId(int value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the customerPostcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPostcode() {
        return customerPostcode;
    }

    /**
     * Sets the value of the customerPostcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPostcode(String value) {
        this.customerPostcode = value;
    }

    /**
     * Gets the value of the customerState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerState() {
        return customerState;
    }

    /**
     * Sets the value of the customerState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerState(String value) {
        this.customerState = value;
    }

    /**
     * Gets the value of the customerStreetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerStreetAddress() {
        return customerStreetAddress;
    }

    /**
     * Sets the value of the customerStreetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerStreetAddress(String value) {
        this.customerStreetAddress = value;
    }

    /**
     * Gets the value of the customerStreetAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerStreetAddress1() {
        return customerStreetAddress1;
    }

    /**
     * Sets the value of the customerStreetAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerStreetAddress1(String value) {
        this.customerStreetAddress1 = value;
    }

    /**
     * Gets the value of the customerSuburb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerSuburb() {
        return customerSuburb;
    }

    /**
     * Sets the value of the customerSuburb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerSuburb(String value) {
        this.customerSuburb = value;
    }

    /**
     * Gets the value of the customerTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerTelephone() {
        return customerTelephone;
    }

    /**
     * Sets the value of the customerTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerTelephone(String value) {
        this.customerTelephone = value;
    }

    /**
     * Gets the value of the customerTelephone1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerTelephone1() {
        return customerTelephone1;
    }

    /**
     * Sets the value of the customerTelephone1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerTelephone1(String value) {
        this.customerTelephone1 = value;
    }

    /**
     * Gets the value of the dateFinished property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateFinished() {
        return dateFinished;
    }

    /**
     * Sets the value of the dateFinished property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateFinished(XMLGregorianCalendar value) {
        this.dateFinished = value;
    }

    /**
     * Gets the value of the datePurchased property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatePurchased() {
        return datePurchased;
    }

    /**
     * Sets the value of the datePurchased property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatePurchased(XMLGregorianCalendar value) {
        this.datePurchased = value;
    }

    /**
     * Gets the value of the deliveryAddrFormatId property.
     * 
     */
    public int getDeliveryAddrFormatId() {
        return deliveryAddrFormatId;
    }

    /**
     * Sets the value of the deliveryAddrFormatId property.
     * 
     */
    public void setDeliveryAddrFormatId(int value) {
        this.deliveryAddrFormatId = value;
    }

    /**
     * Gets the value of the deliveryAddrFormatTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryAddrFormatTemplate() {
        return deliveryAddrFormatTemplate;
    }

    /**
     * Sets the value of the deliveryAddrFormatTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryAddrFormatTemplate(String value) {
        this.deliveryAddrFormatTemplate = value;
    }

    /**
     * Gets the value of the deliveryAddrId property.
     * 
     */
    public int getDeliveryAddrId() {
        return deliveryAddrId;
    }

    /**
     * Sets the value of the deliveryAddrId property.
     * 
     */
    public void setDeliveryAddrId(int value) {
        this.deliveryAddrId = value;
    }

    /**
     * Gets the value of the deliveryCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryCity() {
        return deliveryCity;
    }

    /**
     * Sets the value of the deliveryCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryCity(String value) {
        this.deliveryCity = value;
    }

    /**
     * Gets the value of the deliveryCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * Sets the value of the deliveryCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryCompany(String value) {
        this.deliveryCompany = value;
    }

    /**
     * Gets the value of the deliveryCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryCountry() {
        return deliveryCountry;
    }

    /**
     * Sets the value of the deliveryCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryCountry(String value) {
        this.deliveryCountry = value;
    }

    /**
     * Gets the value of the deliveryCountryObject property.
     * 
     * @return
     *     possible object is
     *     {@link AdminCountry }
     *     
     */
    public AdminCountry getDeliveryCountryObject() {
        return deliveryCountryObject;
    }

    /**
     * Sets the value of the deliveryCountryObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminCountry }
     *     
     */
    public void setDeliveryCountryObject(AdminCountry value) {
        this.deliveryCountryObject = value;
    }

    /**
     * Gets the value of the deliveryEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryEmail() {
        return deliveryEmail;
    }

    /**
     * Sets the value of the deliveryEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryEmail(String value) {
        this.deliveryEmail = value;
    }

    /**
     * Gets the value of the deliveryFormattedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryFormattedAddress() {
        return deliveryFormattedAddress;
    }

    /**
     * Sets the value of the deliveryFormattedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryFormattedAddress(String value) {
        this.deliveryFormattedAddress = value;
    }

    /**
     * Gets the value of the deliveryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryName() {
        return deliveryName;
    }

    /**
     * Sets the value of the deliveryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryName(String value) {
        this.deliveryName = value;
    }

    /**
     * Gets the value of the deliveryPostcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryPostcode() {
        return deliveryPostcode;
    }

    /**
     * Sets the value of the deliveryPostcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryPostcode(String value) {
        this.deliveryPostcode = value;
    }

    /**
     * Gets the value of the deliveryState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryState() {
        return deliveryState;
    }

    /**
     * Sets the value of the deliveryState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryState(String value) {
        this.deliveryState = value;
    }

    /**
     * Gets the value of the deliveryStreetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryStreetAddress() {
        return deliveryStreetAddress;
    }

    /**
     * Sets the value of the deliveryStreetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryStreetAddress(String value) {
        this.deliveryStreetAddress = value;
    }

    /**
     * Gets the value of the deliveryStreetAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryStreetAddress1() {
        return deliveryStreetAddress1;
    }

    /**
     * Sets the value of the deliveryStreetAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryStreetAddress1(String value) {
        this.deliveryStreetAddress1 = value;
    }

    /**
     * Gets the value of the deliverySuburb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliverySuburb() {
        return deliverySuburb;
    }

    /**
     * Sets the value of the deliverySuburb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliverySuburb(String value) {
        this.deliverySuburb = value;
    }

    /**
     * Gets the value of the deliveryTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryTelephone() {
        return deliveryTelephone;
    }

    /**
     * Sets the value of the deliveryTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryTelephone(String value) {
        this.deliveryTelephone = value;
    }

    /**
     * Gets the value of the deliveryTelephone1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryTelephone1() {
        return deliveryTelephone1;
    }

    /**
     * Sets the value of the deliveryTelephone1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryTelephone1(String value) {
        this.deliveryTelephone1 = value;
    }

    /**
     * Gets the value of the deliveryZoneObject property.
     * 
     * @return
     *     possible object is
     *     {@link AdminZone }
     *     
     */
    public AdminZone getDeliveryZoneObject() {
        return deliveryZoneObject;
    }

    /**
     * Sets the value of the deliveryZoneObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminZone }
     *     
     */
    public void setDeliveryZoneObject(AdminZone value) {
        this.deliveryZoneObject = value;
    }

    /**
     * Gets the value of the encKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncKey() {
        return encKey;
    }

    /**
     * Sets the value of the encKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncKey(String value) {
        this.encKey = value;
    }

    /**
     * Gets the value of the formattedTotalIncTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormattedTotalIncTax() {
        return formattedTotalIncTax;
    }

    /**
     * Sets the value of the formattedTotalIncTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormattedTotalIncTax(String value) {
        this.formattedTotalIncTax = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the invoiceFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceFilename() {
        return invoiceFilename;
    }

    /**
     * Sets the value of the invoiceFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceFilename(String value) {
        this.invoiceFilename = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModified(XMLGregorianCalendar value) {
        this.lastModified = value;
    }

    /**
     * Gets the value of the lifecycleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifecycleId() {
        return lifecycleId;
    }

    /**
     * Sets the value of the lifecycleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifecycleId(String value) {
        this.lifecycleId = value;
    }

    /**
     * Gets the value of the locale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocale(String value) {
        this.locale = value;
    }

    /**
     * Gets the value of the numProducts property.
     * 
     */
    public int getNumProducts() {
        return numProducts;
    }

    /**
     * Sets the value of the numProducts property.
     * 
     */
    public void setNumProducts(int value) {
        this.numProducts = value;
    }

    /**
     * Gets the value of the orderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNumber(String value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the orderProducts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderProducts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderProducts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminOrderProduct }
     * 
     * 
     */
    public List<AdminOrderProduct> getOrderProducts() {
        if (orderProducts == null) {
            orderProducts = new ArrayList<AdminOrderProduct>();
        }
        return this.orderProducts;
    }

    /**
     * Gets the value of the orderReturns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderReturns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderReturns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminOrderReturn }
     * 
     * 
     */
    public List<AdminOrderReturn> getOrderReturns() {
        if (orderReturns == null) {
            orderReturns = new ArrayList<AdminOrderReturn>();
        }
        return this.orderReturns;
    }

    /**
     * Gets the value of the orderTotals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderTotals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderTotals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminOrderTotal }
     * 
     * 
     */
    public List<AdminOrderTotal> getOrderTotals() {
        if (orderTotals == null) {
            orderTotals = new ArrayList<AdminOrderTotal>();
        }
        return this.orderTotals;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethod(String value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the paymentModuleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentModuleCode() {
        return paymentModuleCode;
    }

    /**
     * Sets the value of the paymentModuleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentModuleCode(String value) {
        this.paymentModuleCode = value;
    }

    /**
     * Gets the value of the pointsAwarded property.
     * 
     */
    public int getPointsAwarded() {
        return pointsAwarded;
    }

    /**
     * Sets the value of the pointsAwarded property.
     * 
     */
    public void setPointsAwarded(int value) {
        this.pointsAwarded = value;
    }

    /**
     * Gets the value of the pointsRedeemed property.
     * 
     */
    public int getPointsRedeemed() {
        return pointsRedeemed;
    }

    /**
     * Sets the value of the pointsRedeemed property.
     * 
     */
    public void setPointsRedeemed(int value) {
        this.pointsRedeemed = value;
    }

    /**
     * Gets the value of the pointsReservationId property.
     * 
     */
    public int getPointsReservationId() {
        return pointsReservationId;
    }

    /**
     * Sets the value of the pointsReservationId property.
     * 
     */
    public void setPointsReservationId(int value) {
        this.pointsReservationId = value;
    }

    /**
     * Gets the value of the promotionIds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotionIds() {
        return promotionIds;
    }

    /**
     * Sets the value of the promotionIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotionIds(String value) {
        this.promotionIds = value;
    }

    /**
     * Gets the value of the shippingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingMethod() {
        return shippingMethod;
    }

    /**
     * Sets the value of the shippingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingMethod(String value) {
        this.shippingMethod = value;
    }

    /**
     * Gets the value of the shippingModuleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingModuleCode() {
        return shippingModuleCode;
    }

    /**
     * Sets the value of the shippingModuleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingModuleCode(String value) {
        this.shippingModuleCode = value;
    }

    /**
     * Gets the value of the shippingQuote property.
     * 
     * @return
     *     possible object is
     *     {@link AdminShippingQuote }
     *     
     */
    public AdminShippingQuote getShippingQuote() {
        return shippingQuote;
    }

    /**
     * Sets the value of the shippingQuote property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminShippingQuote }
     *     
     */
    public void setShippingQuote(AdminShippingQuote value) {
        this.shippingQuote = value;
    }

    /**
     * Gets the value of the shippingServiceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingServiceCode() {
        return shippingServiceCode;
    }

    /**
     * Sets the value of the shippingServiceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingServiceCode(String value) {
        this.shippingServiceCode = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusText() {
        return statusText;
    }

    /**
     * Sets the value of the statusText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusText(String value) {
        this.statusText = value;
    }

    /**
     * Gets the value of the statusTrail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusTrail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatusTrail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminOrderStatusHistory }
     * 
     * 
     */
    public List<AdminOrderStatusHistory> getStatusTrail() {
        if (statusTrail == null) {
            statusTrail = new ArrayList<AdminOrderStatusHistory>();
        }
        return this.statusTrail;
    }

    /**
     * Gets the value of the tax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTax(BigDecimal value) {
        this.tax = value;
    }

    /**
     * Gets the value of the taxRateObjectArray property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxRateObjectArray property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxRateObjectArray().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminTaxRate }
     * 
     * 
     */
    public List<AdminTaxRate> getTaxRateObjectArray() {
        if (taxRateObjectArray == null) {
            taxRateObjectArray = new ArrayList<AdminTaxRate>();
        }
        return this.taxRateObjectArray;
    }

    /**
     * Gets the value of the totalExTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalExTax() {
        return totalExTax;
    }

    /**
     * Sets the value of the totalExTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalExTax(BigDecimal value) {
        this.totalExTax = value;
    }

    /**
     * Gets the value of the totalIncTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalIncTax() {
        return totalIncTax;
    }

    /**
     * Sets the value of the totalIncTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalIncTax(BigDecimal value) {
        this.totalIncTax = value;
    }

    /**
     * Gets the value of the trackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * Sets the value of the trackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingNumber(String value) {
        this.trackingNumber = value;
    }

}
