//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.29 at 05:07:04 PM BST 
//


package com.oup.eac.domain.migrationtool.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for adminMiscItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adminMiscItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custom1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateAdded" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="itemValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kkMiscItemId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="kkMiscItemTypeId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="kkObjId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="kkObjTypeId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="storeId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adminMiscItem", propOrder = {
    "custom1",
    "custom2",
    "custom3",
    "dateAdded",
    "id",
    "itemValue",
    "kkMiscItemId",
    "kkMiscItemTypeId",
    "kkObjId",
    "kkObjTypeId",
    "storeId"
})
public class AdminMiscItem {

    protected String custom1;
    protected String custom2;
    protected String custom3;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateAdded;
    protected int id;
    protected String itemValue;
    protected int kkMiscItemId;
    protected int kkMiscItemTypeId;
    protected int kkObjId;
    protected int kkObjTypeId;
    protected String storeId;

    /**
     * Gets the value of the custom1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * Sets the value of the custom1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom1(String value) {
        this.custom1 = value;
    }

    /**
     * Gets the value of the custom2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * Sets the value of the custom2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom2(String value) {
        this.custom2 = value;
    }

    /**
     * Gets the value of the custom3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * Sets the value of the custom3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom3(String value) {
        this.custom3 = value;
    }

    /**
     * Gets the value of the dateAdded property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAdded() {
        return dateAdded;
    }

    /**
     * Sets the value of the dateAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAdded(XMLGregorianCalendar value) {
        this.dateAdded = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the itemValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemValue() {
        return itemValue;
    }

    /**
     * Sets the value of the itemValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemValue(String value) {
        this.itemValue = value;
    }

    /**
     * Gets the value of the kkMiscItemId property.
     * 
     */
    public int getKkMiscItemId() {
        return kkMiscItemId;
    }

    /**
     * Sets the value of the kkMiscItemId property.
     * 
     */
    public void setKkMiscItemId(int value) {
        this.kkMiscItemId = value;
    }

    /**
     * Gets the value of the kkMiscItemTypeId property.
     * 
     */
    public int getKkMiscItemTypeId() {
        return kkMiscItemTypeId;
    }

    /**
     * Sets the value of the kkMiscItemTypeId property.
     * 
     */
    public void setKkMiscItemTypeId(int value) {
        this.kkMiscItemTypeId = value;
    }

    /**
     * Gets the value of the kkObjId property.
     * 
     */
    public int getKkObjId() {
        return kkObjId;
    }

    /**
     * Sets the value of the kkObjId property.
     * 
     */
    public void setKkObjId(int value) {
        this.kkObjId = value;
    }

    /**
     * Gets the value of the kkObjTypeId property.
     * 
     */
    public int getKkObjTypeId() {
        return kkObjTypeId;
    }

    /**
     * Sets the value of the kkObjTypeId property.
     * 
     */
    public void setKkObjTypeId(int value) {
        this.kkObjTypeId = value;
    }

    /**
     * Gets the value of the storeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * Sets the value of the storeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreId(String value) {
        this.storeId = value;
    }

}
