//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.29 at 05:07:04 PM BST 
//


package com.oup.eac.domain.migrationtool.beans;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for adminProductXML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adminProductXML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accessoryProducts" type="{}adminProduct" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bundledProducts" type="{}adminProduct" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="crossSellProducts" type="{}adminProduct" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dependentProducts" type="{}adminProduct" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="product" type="{}adminProduct" minOccurs="0"/>
 *         &lt;element name="productTags" type="{}adminTag" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reviews" type="{}adminReview" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="upSellProducts" type="{}adminProduct" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adminProductXML", propOrder = {
    "accessoryProducts",
    "bundledProducts",
    "crossSellProducts",
    "dependentProducts",
    "product",
    "productTags",
    "reviews",
    "upSellProducts"
})
public class AdminProductXML {

    @XmlElement(nillable = true)
    protected List<AdminProduct> accessoryProducts;
    @XmlElement(nillable = true)
    protected List<AdminProduct> bundledProducts;
    @XmlElement(nillable = true)
    protected List<AdminProduct> crossSellProducts;
    @XmlElement(nillable = true)
    protected List<AdminProduct> dependentProducts;
    protected AdminProduct product;
    @XmlElement(nillable = true)
    protected List<AdminTag> productTags;
    @XmlElement(nillable = true)
    protected List<AdminReview> reviews;
    @XmlElement(nillable = true)
    protected List<AdminProduct> upSellProducts;

    /**
     * Gets the value of the accessoryProducts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessoryProducts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessoryProducts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminProduct }
     * 
     * 
     */
    public List<AdminProduct> getAccessoryProducts() {
        if (accessoryProducts == null) {
            accessoryProducts = new ArrayList<AdminProduct>();
        }
        return this.accessoryProducts;
    }

    /**
     * Gets the value of the bundledProducts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bundledProducts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBundledProducts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminProduct }
     * 
     * 
     */
    public List<AdminProduct> getBundledProducts() {
        if (bundledProducts == null) {
            bundledProducts = new ArrayList<AdminProduct>();
        }
        return this.bundledProducts;
    }

    /**
     * Gets the value of the crossSellProducts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the crossSellProducts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCrossSellProducts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminProduct }
     * 
     * 
     */
    public List<AdminProduct> getCrossSellProducts() {
        if (crossSellProducts == null) {
            crossSellProducts = new ArrayList<AdminProduct>();
        }
        return this.crossSellProducts;
    }

    /**
     * Gets the value of the dependentProducts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dependentProducts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDependentProducts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminProduct }
     * 
     * 
     */
    public List<AdminProduct> getDependentProducts() {
        if (dependentProducts == null) {
            dependentProducts = new ArrayList<AdminProduct>();
        }
        return this.dependentProducts;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link AdminProduct }
     *     
     */
    public AdminProduct getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminProduct }
     *     
     */
    public void setProduct(AdminProduct value) {
        this.product = value;
    }

    /**
     * Gets the value of the productTags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productTags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductTags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminTag }
     * 
     * 
     */
    public List<AdminTag> getProductTags() {
        if (productTags == null) {
            productTags = new ArrayList<AdminTag>();
        }
        return this.productTags;
    }

    /**
     * Gets the value of the reviews property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reviews property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReviews().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminReview }
     * 
     * 
     */
    public List<AdminReview> getReviews() {
        if (reviews == null) {
            reviews = new ArrayList<AdminReview>();
        }
        return this.reviews;
    }

    /**
     * Gets the value of the upSellProducts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the upSellProducts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpSellProducts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminProduct }
     * 
     * 
     */
    public List<AdminProduct> getUpSellProducts() {
        if (upSellProducts == null) {
            upSellProducts = new ArrayList<AdminProduct>();
        }
        return this.upSellProducts;
    }

}
