//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.29 at 05:07:04 PM BST 
//


package com.oup.eac.domain.migrationtool.beans;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for adminProduct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adminProduct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attributes" type="{}adminProductAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bookableProd" type="{}adminBookableProduct" minOccurs="0"/>
 *         &lt;element name="bundledProdQuantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="canOrderWhenNotInStock" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="categories" type="{}adminCategory" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="categoryId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="comparison" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom1Dec" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="custom1Int" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="custom2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom2Dec" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="custom2Int" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="custom3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom9" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customAttrArray" type="{}adminProdAttrDesc" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="customAttrs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateAdded" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dateAvailable" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dateLastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="descriptions" type="{}adminProductDescription" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="encodedOptionValues" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="extPrice0" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="extPrice1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="extPrice2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="extPrice3" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="extQuantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="filePath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="formattedPriceExTax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="formattedPriceIncTax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="formattedSpecialPriceExTax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="formattedSpecialPriceIncTax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="image2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="image3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="image4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="indexAttachment" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="invisible" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="manufacturer" type="{}adminManufacturer" minOccurs="0"/>
 *         &lt;element name="manufacturerId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="manufacturerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="masterProdDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="maxDownloadDays" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxNumDownloads" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="miscItems" type="{}adminMiscItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numberReviews" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="opts" type="{}adminOption" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ordered" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="paymentSchedule" type="{}adminPaymentSchedule" minOccurs="0"/>
 *         &lt;element name="paymentScheduleId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="price0" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="price1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="price2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="price3" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="priceExTax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="priceId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="priceIncTax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="productQuantities" type="{}adminProductQuantity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="rating" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specialExpiryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="specialId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="specialPriceExTax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="specialPriceIncTax" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="specialStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="specialStatus" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="stockReorderLevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="storeCustom1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="storeCustom2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="storeCustom3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="taxClassId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="templateId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="templateName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tierPrices" type="{}adminTierPrice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="viewedCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adminProduct", propOrder = {
    "attributes",
    "bookableProd",
    "bundledProdQuantity",
    "canOrderWhenNotInStock",
    "categories",
    "categoryId",
    "comparison",
    "contentType",
    "custom1",
    "custom10",
    "custom1Dec",
    "custom1Int",
    "custom2",
    "custom2Dec",
    "custom2Int",
    "custom3",
    "custom4",
    "custom5",
    "custom6",
    "custom7",
    "custom8",
    "custom9",
    "customAttrArray",
    "customAttrs",
    "dateAdded",
    "dateAvailable",
    "dateLastModified",
    "description",
    "descriptions",
    "encodedOptionValues",
    "expiryDate",
    "extPrice0",
    "extPrice1",
    "extPrice2",
    "extPrice3",
    "extQuantity",
    "filePath",
    "formattedPriceExTax",
    "formattedPriceIncTax",
    "formattedSpecialPriceExTax",
    "formattedSpecialPriceIncTax",
    "id",
    "image",
    "image2",
    "image3",
    "image4",
    "indexAttachment",
    "invisible",
    "manufacturer",
    "manufacturerId",
    "manufacturerName",
    "masterProdDate",
    "maxDownloadDays",
    "maxNumDownloads",
    "miscItems",
    "model",
    "name",
    "numberReviews",
    "opts",
    "ordered",
    "paymentSchedule",
    "paymentScheduleId",
    "price0",
    "price1",
    "price2",
    "price3",
    "priceExTax",
    "priceId",
    "priceIncTax",
    "productQuantities",
    "quantity",
    "rating",
    "sku",
    "specialExpiryDate",
    "specialId",
    "specialPriceExTax",
    "specialPriceIncTax",
    "specialStartDate",
    "specialStatus",
    "status",
    "stockReorderLevel",
    "storeCustom1",
    "storeCustom2",
    "storeCustom3",
    "taxClassId",
    "templateId",
    "templateName",
    "tierPrices",
    "type",
    "url",
    "uuid",
    "viewedCount",
    "weight"
})
public class AdminProduct {

    @XmlElement(nillable = true)
    protected List<AdminProductAttribute> attributes;
    protected AdminBookableProduct bookableProd;
    protected int bundledProdQuantity;
    protected Boolean canOrderWhenNotInStock;
    @XmlElement(nillable = true)
    protected List<AdminCategory> categories;
    protected int categoryId;
    protected String comparison;
    protected String contentType;
    protected String custom1;
    protected String custom10;
    protected BigDecimal custom1Dec;
    protected int custom1Int;
    protected String custom2;
    protected BigDecimal custom2Dec;
    protected int custom2Int;
    protected String custom3;
    protected String custom4;
    protected String custom5;
    protected String custom6;
    protected String custom7;
    protected String custom8;
    protected String custom9;
    @XmlElement(nillable = true)
    protected List<AdminProdAttrDesc> customAttrArray;
    protected String customAttrs;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateAdded;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateAvailable;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateLastModified;
    protected String description;
    @XmlElement(nillable = true)
    protected List<AdminProductDescription> descriptions;
    protected String encodedOptionValues;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expiryDate;
    protected BigDecimal extPrice0;
    protected BigDecimal extPrice1;
    protected BigDecimal extPrice2;
    protected BigDecimal extPrice3;
    protected Integer extQuantity;
    protected String filePath;
    protected String formattedPriceExTax;
    protected String formattedPriceIncTax;
    protected String formattedSpecialPriceExTax;
    protected String formattedSpecialPriceIncTax;
    protected int id;
    protected String image;
    protected String image2;
    protected String image3;
    protected String image4;
    protected boolean indexAttachment;
    protected byte invisible;
    protected AdminManufacturer manufacturer;
    protected int manufacturerId;
    protected String manufacturerName;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar masterProdDate;
    protected int maxDownloadDays;
    protected int maxNumDownloads;
    @XmlElement(nillable = true)
    protected List<AdminMiscItem> miscItems;
    protected String model;
    protected String name;
    protected int numberReviews;
    @XmlElement(nillable = true)
    protected List<AdminOption> opts;
    protected int ordered;
    protected AdminPaymentSchedule paymentSchedule;
    protected int paymentScheduleId;
    protected BigDecimal price0;
    protected BigDecimal price1;
    protected BigDecimal price2;
    protected BigDecimal price3;
    protected BigDecimal priceExTax;
    protected int priceId;
    protected BigDecimal priceIncTax;
    @XmlElement(nillable = true)
    protected List<AdminProductQuantity> productQuantities;
    protected int quantity;
    protected BigDecimal rating;
    protected String sku;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar specialExpiryDate;
    protected int specialId;
    protected BigDecimal specialPriceExTax;
    protected BigDecimal specialPriceIncTax;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar specialStartDate;
    protected byte specialStatus;
    protected byte status;
    protected int stockReorderLevel;
    protected String storeCustom1;
    protected String storeCustom2;
    protected String storeCustom3;
    protected int taxClassId;
    protected int templateId;
    protected String templateName;
    @XmlElement(nillable = true)
    protected List<AdminTierPrice> tierPrices;
    protected int type;
    protected String url;
    protected String uuid;
    protected int viewedCount;
    protected BigDecimal weight;

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminProductAttribute }
     * 
     * 
     */
    public List<AdminProductAttribute> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<AdminProductAttribute>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the bookableProd property.
     * 
     * @return
     *     possible object is
     *     {@link AdminBookableProduct }
     *     
     */
    public AdminBookableProduct getBookableProd() {
        return bookableProd;
    }

    /**
     * Sets the value of the bookableProd property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminBookableProduct }
     *     
     */
    public void setBookableProd(AdminBookableProduct value) {
        this.bookableProd = value;
    }

    /**
     * Gets the value of the bundledProdQuantity property.
     * 
     */
    public int getBundledProdQuantity() {
        return bundledProdQuantity;
    }

    /**
     * Sets the value of the bundledProdQuantity property.
     * 
     */
    public void setBundledProdQuantity(int value) {
        this.bundledProdQuantity = value;
    }

    /**
     * Gets the value of the canOrderWhenNotInStock property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanOrderWhenNotInStock() {
        return canOrderWhenNotInStock;
    }

    /**
     * Sets the value of the canOrderWhenNotInStock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanOrderWhenNotInStock(Boolean value) {
        this.canOrderWhenNotInStock = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminCategory }
     * 
     * 
     */
    public List<AdminCategory> getCategories() {
        if (categories == null) {
            categories = new ArrayList<AdminCategory>();
        }
        return this.categories;
    }

    /**
     * Gets the value of the categoryId property.
     * 
     */
    public int getCategoryId() {
        return categoryId;
    }

    /**
     * Sets the value of the categoryId property.
     * 
     */
    public void setCategoryId(int value) {
        this.categoryId = value;
    }

    /**
     * Gets the value of the comparison property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComparison() {
        return comparison;
    }

    /**
     * Sets the value of the comparison property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComparison(String value) {
        this.comparison = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the custom1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * Sets the value of the custom1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom1(String value) {
        this.custom1 = value;
    }

    /**
     * Gets the value of the custom10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom10() {
        return custom10;
    }

    /**
     * Sets the value of the custom10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom10(String value) {
        this.custom10 = value;
    }

    /**
     * Gets the value of the custom1Dec property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCustom1Dec() {
        return custom1Dec;
    }

    /**
     * Sets the value of the custom1Dec property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCustom1Dec(BigDecimal value) {
        this.custom1Dec = value;
    }

    /**
     * Gets the value of the custom1Int property.
     * 
     */
    public int getCustom1Int() {
        return custom1Int;
    }

    /**
     * Sets the value of the custom1Int property.
     * 
     */
    public void setCustom1Int(int value) {
        this.custom1Int = value;
    }

    /**
     * Gets the value of the custom2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * Sets the value of the custom2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom2(String value) {
        this.custom2 = value;
    }

    /**
     * Gets the value of the custom2Dec property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCustom2Dec() {
        return custom2Dec;
    }

    /**
     * Sets the value of the custom2Dec property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCustom2Dec(BigDecimal value) {
        this.custom2Dec = value;
    }

    /**
     * Gets the value of the custom2Int property.
     * 
     */
    public int getCustom2Int() {
        return custom2Int;
    }

    /**
     * Sets the value of the custom2Int property.
     * 
     */
    public void setCustom2Int(int value) {
        this.custom2Int = value;
    }

    /**
     * Gets the value of the custom3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * Sets the value of the custom3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom3(String value) {
        this.custom3 = value;
    }

    /**
     * Gets the value of the custom4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * Sets the value of the custom4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom4(String value) {
        this.custom4 = value;
    }

    /**
     * Gets the value of the custom5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * Sets the value of the custom5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom5(String value) {
        this.custom5 = value;
    }

    /**
     * Gets the value of the custom6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom6() {
        return custom6;
    }

    /**
     * Sets the value of the custom6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom6(String value) {
        this.custom6 = value;
    }

    /**
     * Gets the value of the custom7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom7() {
        return custom7;
    }

    /**
     * Sets the value of the custom7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom7(String value) {
        this.custom7 = value;
    }

    /**
     * Gets the value of the custom8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom8() {
        return custom8;
    }

    /**
     * Sets the value of the custom8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom8(String value) {
        this.custom8 = value;
    }

    /**
     * Gets the value of the custom9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom9() {
        return custom9;
    }

    /**
     * Sets the value of the custom9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom9(String value) {
        this.custom9 = value;
    }

    /**
     * Gets the value of the customAttrArray property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customAttrArray property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomAttrArray().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminProdAttrDesc }
     * 
     * 
     */
    public List<AdminProdAttrDesc> getCustomAttrArray() {
        if (customAttrArray == null) {
            customAttrArray = new ArrayList<AdminProdAttrDesc>();
        }
        return this.customAttrArray;
    }

    /**
     * Gets the value of the customAttrs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomAttrs() {
        return customAttrs;
    }

    /**
     * Sets the value of the customAttrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomAttrs(String value) {
        this.customAttrs = value;
    }

    /**
     * Gets the value of the dateAdded property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAdded() {
        return dateAdded;
    }

    /**
     * Sets the value of the dateAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAdded(XMLGregorianCalendar value) {
        this.dateAdded = value;
    }

    /**
     * Gets the value of the dateAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAvailable() {
        return dateAvailable;
    }

    /**
     * Sets the value of the dateAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAvailable(XMLGregorianCalendar value) {
        this.dateAvailable = value;
    }

    /**
     * Gets the value of the dateLastModified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateLastModified() {
        return dateLastModified;
    }

    /**
     * Sets the value of the dateLastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateLastModified(XMLGregorianCalendar value) {
        this.dateLastModified = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescriptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminProductDescription }
     * 
     * 
     */
    public List<AdminProductDescription> getDescriptions() {
        if (descriptions == null) {
            descriptions = new ArrayList<AdminProductDescription>();
        }
        return this.descriptions;
    }

    /**
     * Gets the value of the encodedOptionValues property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncodedOptionValues() {
        return encodedOptionValues;
    }

    /**
     * Sets the value of the encodedOptionValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncodedOptionValues(String value) {
        this.encodedOptionValues = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the extPrice0 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExtPrice0() {
        return extPrice0;
    }

    /**
     * Sets the value of the extPrice0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExtPrice0(BigDecimal value) {
        this.extPrice0 = value;
    }

    /**
     * Gets the value of the extPrice1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExtPrice1() {
        return extPrice1;
    }

    /**
     * Sets the value of the extPrice1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExtPrice1(BigDecimal value) {
        this.extPrice1 = value;
    }

    /**
     * Gets the value of the extPrice2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExtPrice2() {
        return extPrice2;
    }

    /**
     * Sets the value of the extPrice2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExtPrice2(BigDecimal value) {
        this.extPrice2 = value;
    }

    /**
     * Gets the value of the extPrice3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExtPrice3() {
        return extPrice3;
    }

    /**
     * Sets the value of the extPrice3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExtPrice3(BigDecimal value) {
        this.extPrice3 = value;
    }

    /**
     * Gets the value of the extQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExtQuantity() {
        return extQuantity;
    }

    /**
     * Sets the value of the extQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExtQuantity(Integer value) {
        this.extQuantity = value;
    }

    /**
     * Gets the value of the filePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * Sets the value of the filePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilePath(String value) {
        this.filePath = value;
    }

    /**
     * Gets the value of the formattedPriceExTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormattedPriceExTax() {
        return formattedPriceExTax;
    }

    /**
     * Sets the value of the formattedPriceExTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormattedPriceExTax(String value) {
        this.formattedPriceExTax = value;
    }

    /**
     * Gets the value of the formattedPriceIncTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormattedPriceIncTax() {
        return formattedPriceIncTax;
    }

    /**
     * Sets the value of the formattedPriceIncTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormattedPriceIncTax(String value) {
        this.formattedPriceIncTax = value;
    }

    /**
     * Gets the value of the formattedSpecialPriceExTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormattedSpecialPriceExTax() {
        return formattedSpecialPriceExTax;
    }

    /**
     * Sets the value of the formattedSpecialPriceExTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormattedSpecialPriceExTax(String value) {
        this.formattedSpecialPriceExTax = value;
    }

    /**
     * Gets the value of the formattedSpecialPriceIncTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormattedSpecialPriceIncTax() {
        return formattedSpecialPriceIncTax;
    }

    /**
     * Sets the value of the formattedSpecialPriceIncTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormattedSpecialPriceIncTax(String value) {
        this.formattedSpecialPriceIncTax = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the image2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage2() {
        return image2;
    }

    /**
     * Sets the value of the image2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage2(String value) {
        this.image2 = value;
    }

    /**
     * Gets the value of the image3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage3() {
        return image3;
    }

    /**
     * Sets the value of the image3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage3(String value) {
        this.image3 = value;
    }

    /**
     * Gets the value of the image4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage4() {
        return image4;
    }

    /**
     * Sets the value of the image4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage4(String value) {
        this.image4 = value;
    }

    /**
     * Gets the value of the indexAttachment property.
     * 
     */
    public boolean isIndexAttachment() {
        return indexAttachment;
    }

    /**
     * Sets the value of the indexAttachment property.
     * 
     */
    public void setIndexAttachment(boolean value) {
        this.indexAttachment = value;
    }

    /**
     * Gets the value of the invisible property.
     * 
     */
    public byte getInvisible() {
        return invisible;
    }

    /**
     * Sets the value of the invisible property.
     * 
     */
    public void setInvisible(byte value) {
        this.invisible = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link AdminManufacturer }
     *     
     */
    public AdminManufacturer getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminManufacturer }
     *     
     */
    public void setManufacturer(AdminManufacturer value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the manufacturerId property.
     * 
     */
    public int getManufacturerId() {
        return manufacturerId;
    }

    /**
     * Sets the value of the manufacturerId property.
     * 
     */
    public void setManufacturerId(int value) {
        this.manufacturerId = value;
    }

    /**
     * Gets the value of the manufacturerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerName() {
        return manufacturerName;
    }

    /**
     * Sets the value of the manufacturerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerName(String value) {
        this.manufacturerName = value;
    }

    /**
     * Gets the value of the masterProdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMasterProdDate() {
        return masterProdDate;
    }

    /**
     * Sets the value of the masterProdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMasterProdDate(XMLGregorianCalendar value) {
        this.masterProdDate = value;
    }

    /**
     * Gets the value of the maxDownloadDays property.
     * 
     */
    public int getMaxDownloadDays() {
        return maxDownloadDays;
    }

    /**
     * Sets the value of the maxDownloadDays property.
     * 
     */
    public void setMaxDownloadDays(int value) {
        this.maxDownloadDays = value;
    }

    /**
     * Gets the value of the maxNumDownloads property.
     * 
     */
    public int getMaxNumDownloads() {
        return maxNumDownloads;
    }

    /**
     * Sets the value of the maxNumDownloads property.
     * 
     */
    public void setMaxNumDownloads(int value) {
        this.maxNumDownloads = value;
    }

    /**
     * Gets the value of the miscItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the miscItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMiscItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminMiscItem }
     * 
     * 
     */
    public List<AdminMiscItem> getMiscItems() {
        if (miscItems == null) {
            miscItems = new ArrayList<AdminMiscItem>();
        }
        return this.miscItems;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the numberReviews property.
     * 
     */
    public int getNumberReviews() {
        return numberReviews;
    }

    /**
     * Sets the value of the numberReviews property.
     * 
     */
    public void setNumberReviews(int value) {
        this.numberReviews = value;
    }

    /**
     * Gets the value of the opts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminOption }
     * 
     * 
     */
    public List<AdminOption> getOpts() {
        if (opts == null) {
            opts = new ArrayList<AdminOption>();
        }
        return this.opts;
    }

    /**
     * Gets the value of the ordered property.
     * 
     */
    public int getOrdered() {
        return ordered;
    }

    /**
     * Sets the value of the ordered property.
     * 
     */
    public void setOrdered(int value) {
        this.ordered = value;
    }

    /**
     * Gets the value of the paymentSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link AdminPaymentSchedule }
     *     
     */
    public AdminPaymentSchedule getPaymentSchedule() {
        return paymentSchedule;
    }

    /**
     * Sets the value of the paymentSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminPaymentSchedule }
     *     
     */
    public void setPaymentSchedule(AdminPaymentSchedule value) {
        this.paymentSchedule = value;
    }

    /**
     * Gets the value of the paymentScheduleId property.
     * 
     */
    public int getPaymentScheduleId() {
        return paymentScheduleId;
    }

    /**
     * Sets the value of the paymentScheduleId property.
     * 
     */
    public void setPaymentScheduleId(int value) {
        this.paymentScheduleId = value;
    }

    /**
     * Gets the value of the price0 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice0() {
        return price0;
    }

    /**
     * Sets the value of the price0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice0(BigDecimal value) {
        this.price0 = value;
    }

    /**
     * Gets the value of the price1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice1() {
        return price1;
    }

    /**
     * Sets the value of the price1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice1(BigDecimal value) {
        this.price1 = value;
    }

    /**
     * Gets the value of the price2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice2() {
        return price2;
    }

    /**
     * Sets the value of the price2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice2(BigDecimal value) {
        this.price2 = value;
    }

    /**
     * Gets the value of the price3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice3() {
        return price3;
    }

    /**
     * Sets the value of the price3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice3(BigDecimal value) {
        this.price3 = value;
    }

    /**
     * Gets the value of the priceExTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceExTax() {
        return priceExTax;
    }

    /**
     * Sets the value of the priceExTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceExTax(BigDecimal value) {
        this.priceExTax = value;
    }

    /**
     * Gets the value of the priceId property.
     * 
     */
    public int getPriceId() {
        return priceId;
    }

    /**
     * Sets the value of the priceId property.
     * 
     */
    public void setPriceId(int value) {
        this.priceId = value;
    }

    /**
     * Gets the value of the priceIncTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriceIncTax() {
        return priceIncTax;
    }

    /**
     * Sets the value of the priceIncTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriceIncTax(BigDecimal value) {
        this.priceIncTax = value;
    }

    /**
     * Gets the value of the productQuantities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productQuantities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductQuantities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminProductQuantity }
     * 
     * 
     */
    public List<AdminProductQuantity> getProductQuantities() {
        if (productQuantities == null) {
            productQuantities = new ArrayList<AdminProductQuantity>();
        }
        return this.productQuantities;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRating(BigDecimal value) {
        this.rating = value;
    }

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSku() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSku(String value) {
        this.sku = value;
    }

    /**
     * Gets the value of the specialExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSpecialExpiryDate() {
        return specialExpiryDate;
    }

    /**
     * Sets the value of the specialExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSpecialExpiryDate(XMLGregorianCalendar value) {
        this.specialExpiryDate = value;
    }

    /**
     * Gets the value of the specialId property.
     * 
     */
    public int getSpecialId() {
        return specialId;
    }

    /**
     * Sets the value of the specialId property.
     * 
     */
    public void setSpecialId(int value) {
        this.specialId = value;
    }

    /**
     * Gets the value of the specialPriceExTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpecialPriceExTax() {
        return specialPriceExTax;
    }

    /**
     * Sets the value of the specialPriceExTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpecialPriceExTax(BigDecimal value) {
        this.specialPriceExTax = value;
    }

    /**
     * Gets the value of the specialPriceIncTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpecialPriceIncTax() {
        return specialPriceIncTax;
    }

    /**
     * Sets the value of the specialPriceIncTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpecialPriceIncTax(BigDecimal value) {
        this.specialPriceIncTax = value;
    }

    /**
     * Gets the value of the specialStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSpecialStartDate() {
        return specialStartDate;
    }

    /**
     * Sets the value of the specialStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSpecialStartDate(XMLGregorianCalendar value) {
        this.specialStartDate = value;
    }

    /**
     * Gets the value of the specialStatus property.
     * 
     */
    public byte getSpecialStatus() {
        return specialStatus;
    }

    /**
     * Sets the value of the specialStatus property.
     * 
     */
    public void setSpecialStatus(byte value) {
        this.specialStatus = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public byte getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(byte value) {
        this.status = value;
    }

    /**
     * Gets the value of the stockReorderLevel property.
     * 
     */
    public int getStockReorderLevel() {
        return stockReorderLevel;
    }

    /**
     * Sets the value of the stockReorderLevel property.
     * 
     */
    public void setStockReorderLevel(int value) {
        this.stockReorderLevel = value;
    }

    /**
     * Gets the value of the storeCustom1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreCustom1() {
        return storeCustom1;
    }

    /**
     * Sets the value of the storeCustom1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreCustom1(String value) {
        this.storeCustom1 = value;
    }

    /**
     * Gets the value of the storeCustom2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreCustom2() {
        return storeCustom2;
    }

    /**
     * Sets the value of the storeCustom2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreCustom2(String value) {
        this.storeCustom2 = value;
    }

    /**
     * Gets the value of the storeCustom3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreCustom3() {
        return storeCustom3;
    }

    /**
     * Sets the value of the storeCustom3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreCustom3(String value) {
        this.storeCustom3 = value;
    }

    /**
     * Gets the value of the taxClassId property.
     * 
     */
    public int getTaxClassId() {
        return taxClassId;
    }

    /**
     * Sets the value of the taxClassId property.
     * 
     */
    public void setTaxClassId(int value) {
        this.taxClassId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     */
    public int getTemplateId() {
        return templateId;
    }

    /**
     * Sets the value of the templateId property.
     * 
     */
    public void setTemplateId(int value) {
        this.templateId = value;
    }

    /**
     * Gets the value of the templateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * Sets the value of the templateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateName(String value) {
        this.templateName = value;
    }

    /**
     * Gets the value of the tierPrices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tierPrices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTierPrices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminTierPrice }
     * 
     * 
     */
    public List<AdminTierPrice> getTierPrices() {
        if (tierPrices == null) {
            tierPrices = new ArrayList<AdminTierPrice>();
        }
        return this.tierPrices;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public int getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     */
    public void setType(int value) {
        this.type = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the viewedCount property.
     * 
     */
    public int getViewedCount() {
        return viewedCount;
    }

    /**
     * Sets the value of the viewedCount property.
     * 
     */
    public void setViewedCount(int value) {
        this.viewedCount = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeight(BigDecimal value) {
        this.weight = value;
    }

}
