//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.29 at 05:07:04 PM BST 
//


package com.oup.eac.domain.migrationtool.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for adminPanel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adminPanel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="canDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="canEdit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="canInsert" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom1" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="custom1Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom2" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="custom2Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom3" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="custom3Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom4" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="custom4Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom5" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="custom5Desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateAdded" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adminPanel", propOrder = {
    "canDelete",
    "canEdit",
    "canInsert",
    "code",
    "custom1",
    "custom1Desc",
    "custom2",
    "custom2Desc",
    "custom3",
    "custom3Desc",
    "custom4",
    "custom4Desc",
    "custom5",
    "custom5Desc",
    "dateAdded",
    "description",
    "id",
    "lastModified"
})
public class AdminPanel {

    protected boolean canDelete;
    protected boolean canEdit;
    protected boolean canInsert;
    protected String code;
    protected boolean custom1;
    protected String custom1Desc;
    protected boolean custom2;
    protected String custom2Desc;
    protected boolean custom3;
    protected String custom3Desc;
    protected boolean custom4;
    protected String custom4Desc;
    protected boolean custom5;
    protected String custom5Desc;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateAdded;
    protected String description;
    protected int id;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModified;

    /**
     * Gets the value of the canDelete property.
     * 
     */
    public boolean isCanDelete() {
        return canDelete;
    }

    /**
     * Sets the value of the canDelete property.
     * 
     */
    public void setCanDelete(boolean value) {
        this.canDelete = value;
    }

    /**
     * Gets the value of the canEdit property.
     * 
     */
    public boolean isCanEdit() {
        return canEdit;
    }

    /**
     * Sets the value of the canEdit property.
     * 
     */
    public void setCanEdit(boolean value) {
        this.canEdit = value;
    }

    /**
     * Gets the value of the canInsert property.
     * 
     */
    public boolean isCanInsert() {
        return canInsert;
    }

    /**
     * Sets the value of the canInsert property.
     * 
     */
    public void setCanInsert(boolean value) {
        this.canInsert = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the custom1 property.
     * 
     */
    public boolean isCustom1() {
        return custom1;
    }

    /**
     * Sets the value of the custom1 property.
     * 
     */
    public void setCustom1(boolean value) {
        this.custom1 = value;
    }

    /**
     * Gets the value of the custom1Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom1Desc() {
        return custom1Desc;
    }

    /**
     * Sets the value of the custom1Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom1Desc(String value) {
        this.custom1Desc = value;
    }

    /**
     * Gets the value of the custom2 property.
     * 
     */
    public boolean isCustom2() {
        return custom2;
    }

    /**
     * Sets the value of the custom2 property.
     * 
     */
    public void setCustom2(boolean value) {
        this.custom2 = value;
    }

    /**
     * Gets the value of the custom2Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom2Desc() {
        return custom2Desc;
    }

    /**
     * Sets the value of the custom2Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom2Desc(String value) {
        this.custom2Desc = value;
    }

    /**
     * Gets the value of the custom3 property.
     * 
     */
    public boolean isCustom3() {
        return custom3;
    }

    /**
     * Sets the value of the custom3 property.
     * 
     */
    public void setCustom3(boolean value) {
        this.custom3 = value;
    }

    /**
     * Gets the value of the custom3Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom3Desc() {
        return custom3Desc;
    }

    /**
     * Sets the value of the custom3Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom3Desc(String value) {
        this.custom3Desc = value;
    }

    /**
     * Gets the value of the custom4 property.
     * 
     */
    public boolean isCustom4() {
        return custom4;
    }

    /**
     * Sets the value of the custom4 property.
     * 
     */
    public void setCustom4(boolean value) {
        this.custom4 = value;
    }

    /**
     * Gets the value of the custom4Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom4Desc() {
        return custom4Desc;
    }

    /**
     * Sets the value of the custom4Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom4Desc(String value) {
        this.custom4Desc = value;
    }

    /**
     * Gets the value of the custom5 property.
     * 
     */
    public boolean isCustom5() {
        return custom5;
    }

    /**
     * Sets the value of the custom5 property.
     * 
     */
    public void setCustom5(boolean value) {
        this.custom5 = value;
    }

    /**
     * Gets the value of the custom5Desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom5Desc() {
        return custom5Desc;
    }

    /**
     * Sets the value of the custom5Desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom5Desc(String value) {
        this.custom5Desc = value;
    }

    /**
     * Gets the value of the dateAdded property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAdded() {
        return dateAdded;
    }

    /**
     * Sets the value of the dateAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAdded(XMLGregorianCalendar value) {
        this.dateAdded = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModified(XMLGregorianCalendar value) {
        this.lastModified = value;
    }

}
