//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.29 at 05:07:04 PM BST 
//


package com.oup.eac.domain.migrationtool.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for adminZone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="adminZone">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custom1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custom3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="zoneCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="zoneCountryCatKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="zoneCountryId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="zoneCountryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="zoneId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="zoneInvisible" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="zoneName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="zoneSearch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adminZone", propOrder = {
    "custom1",
    "custom2",
    "custom3",
    "id",
    "zoneCode",
    "zoneCountryCatKey",
    "zoneCountryId",
    "zoneCountryName",
    "zoneId",
    "zoneInvisible",
    "zoneName",
    "zoneSearch"
})
public class AdminZone {

    protected String custom1;
    protected String custom2;
    protected String custom3;
    protected int id;
    protected String zoneCode;
    protected String zoneCountryCatKey;
    protected int zoneCountryId;
    protected String zoneCountryName;
    protected int zoneId;
    protected boolean zoneInvisible;
    protected String zoneName;
    protected String zoneSearch;

    /**
     * Gets the value of the custom1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * Sets the value of the custom1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom1(String value) {
        this.custom1 = value;
    }

    /**
     * Gets the value of the custom2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * Sets the value of the custom2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom2(String value) {
        this.custom2 = value;
    }

    /**
     * Gets the value of the custom3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * Sets the value of the custom3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom3(String value) {
        this.custom3 = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the zoneCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneCode() {
        return zoneCode;
    }

    /**
     * Sets the value of the zoneCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneCode(String value) {
        this.zoneCode = value;
    }

    /**
     * Gets the value of the zoneCountryCatKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneCountryCatKey() {
        return zoneCountryCatKey;
    }

    /**
     * Sets the value of the zoneCountryCatKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneCountryCatKey(String value) {
        this.zoneCountryCatKey = value;
    }

    /**
     * Gets the value of the zoneCountryId property.
     * 
     */
    public int getZoneCountryId() {
        return zoneCountryId;
    }

    /**
     * Sets the value of the zoneCountryId property.
     * 
     */
    public void setZoneCountryId(int value) {
        this.zoneCountryId = value;
    }

    /**
     * Gets the value of the zoneCountryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneCountryName() {
        return zoneCountryName;
    }

    /**
     * Sets the value of the zoneCountryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneCountryName(String value) {
        this.zoneCountryName = value;
    }

    /**
     * Gets the value of the zoneId property.
     * 
     */
    public int getZoneId() {
        return zoneId;
    }

    /**
     * Sets the value of the zoneId property.
     * 
     */
    public void setZoneId(int value) {
        this.zoneId = value;
    }

    /**
     * Gets the value of the zoneInvisible property.
     * 
     */
    public boolean isZoneInvisible() {
        return zoneInvisible;
    }

    /**
     * Sets the value of the zoneInvisible property.
     * 
     */
    public void setZoneInvisible(boolean value) {
        this.zoneInvisible = value;
    }

    /**
     * Gets the value of the zoneName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneName() {
        return zoneName;
    }

    /**
     * Sets the value of the zoneName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneName(String value) {
        this.zoneName = value;
    }

    /**
     * Gets the value of the zoneSearch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoneSearch() {
        return zoneSearch;
    }

    /**
     * Sets the value of the zoneSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoneSearch(String value) {
        this.zoneSearch = value;
    }

}
