//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.29 at 05:07:04 PM BST 
//


package com.oup.eac.domain.migrationtool.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for kkConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kkConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="configurationDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="configurationGroupId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="configurationId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="configurationKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="configurationTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="configurationValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateAdded" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="returnByApi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="setFunction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sortOrder" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="statusId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="useFunction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kkConfiguration", propOrder = {
    "configurationDescription",
    "configurationGroupId",
    "configurationId",
    "configurationKey",
    "configurationTitle",
    "configurationValue",
    "dateAdded",
    "id",
    "lastModified",
    "returnByApi",
    "setFunction",
    "sortOrder",
    "statusId",
    "useFunction"
})
public class KkConfiguration {

    protected String configurationDescription;
    protected int configurationGroupId;
    protected int configurationId;
    protected String configurationKey;
    protected String configurationTitle;
    protected String configurationValue;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateAdded;
    protected int id;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModified;
    protected boolean returnByApi;
    protected String setFunction;
    protected int sortOrder;
    protected int statusId;
    protected String useFunction;

    /**
     * Gets the value of the configurationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationDescription() {
        return configurationDescription;
    }

    /**
     * Sets the value of the configurationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationDescription(String value) {
        this.configurationDescription = value;
    }

    /**
     * Gets the value of the configurationGroupId property.
     * 
     */
    public int getConfigurationGroupId() {
        return configurationGroupId;
    }

    /**
     * Sets the value of the configurationGroupId property.
     * 
     */
    public void setConfigurationGroupId(int value) {
        this.configurationGroupId = value;
    }

    /**
     * Gets the value of the configurationId property.
     * 
     */
    public int getConfigurationId() {
        return configurationId;
    }

    /**
     * Sets the value of the configurationId property.
     * 
     */
    public void setConfigurationId(int value) {
        this.configurationId = value;
    }

    /**
     * Gets the value of the configurationKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationKey() {
        return configurationKey;
    }

    /**
     * Sets the value of the configurationKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationKey(String value) {
        this.configurationKey = value;
    }

    /**
     * Gets the value of the configurationTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationTitle() {
        return configurationTitle;
    }

    /**
     * Sets the value of the configurationTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationTitle(String value) {
        this.configurationTitle = value;
    }

    /**
     * Gets the value of the configurationValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationValue() {
        return configurationValue;
    }

    /**
     * Sets the value of the configurationValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationValue(String value) {
        this.configurationValue = value;
    }

    /**
     * Gets the value of the dateAdded property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAdded() {
        return dateAdded;
    }

    /**
     * Sets the value of the dateAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAdded(XMLGregorianCalendar value) {
        this.dateAdded = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModified(XMLGregorianCalendar value) {
        this.lastModified = value;
    }

    /**
     * Gets the value of the returnByApi property.
     * 
     */
    public boolean isReturnByApi() {
        return returnByApi;
    }

    /**
     * Sets the value of the returnByApi property.
     * 
     */
    public void setReturnByApi(boolean value) {
        this.returnByApi = value;
    }

    /**
     * Gets the value of the setFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetFunction() {
        return setFunction;
    }

    /**
     * Sets the value of the setFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetFunction(String value) {
        this.setFunction = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     */
    public int getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     */
    public void setSortOrder(int value) {
        this.sortOrder = value;
    }

    /**
     * Gets the value of the statusId property.
     * 
     */
    public int getStatusId() {
        return statusId;
    }

    /**
     * Sets the value of the statusId property.
     * 
     */
    public void setStatusId(int value) {
        this.statusId = value;
    }

    /**
     * Gets the value of the useFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseFunction() {
        return useFunction;
    }

    /**
     * Sets the value of the useFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseFunction(String value) {
        this.useFunction = value;
    }

}
